version: '3.8'

services:
  backend:
    image: duongthiendinh/mern-backend:1.0
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://<db_username>:<db_password>@cluster0.u8oznzw.mongodb.net/?appName=Cluster0
    restart: always

  frontend:
    image: duongthiendinh/mern-frontend:1.0
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
