services:
  backend:
    image: duongthiendinh/mern-backend:1.0
    network_mode: "host"
    environment:
      - MONGODB_URI=mongodb+srv://admin:admin123@cluster0.u8oznzw.mongodb.net/school?retryWrites=true&w=majority
    restart: always

  frontend:
    image: duongthiendinh/mern-frontend:2.0
    ports:
      - "3000:3000"
    restart: always
